CREATE TABLE IF NOT EXISTS users(
   id UUID PRIMARY KEY,
   username VARCHAR (50) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL,
   password VARCHAR (512) NOT NULL,
   created_at TIMESTAMP NOT NULL,
   updated_at TIMESTAMP NOT NULL
);