version: '3.7'

services:

  go:
    image: golang:1.13-buster
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - FIRESTORE_EMULATOR_HOST=localhost:8442
    ports:
      - "8000:8000"
    command: ["go", "test", "./tests/...", "-v"]
