version: '3.7'

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - ./mbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    ports:
      - 5432:5432
